apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: weather-streaming-to-bronze
  namespace: default
spec:
  type: Python
  mode: cluster
  sparkVersion: 3.3.3

  image: spark-weather-kafka:3.3.3-r6
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///app/stream_weather_to_bronze.py

  restartPolicy:
    type: Always

  sparkConf:
    spark.sql.streaming.stopGracefullyOnShutdown: "true"
    spark.kubernetes.executor.deleteOnTermination: "true"
    spark.kafka.bootstrap.servers: kafka-kafka-bootstrap.data:9092

  driver:
    cores: 1
    memory: 1g
    serviceAccount: spark
    env:
      - name: KAFKA_BOOTSTRAP
        value: kafka-kafka-bootstrap.data.svc.cluster.local:9092
      - name: KAFKA_TOPIC
        value: weather-raw
      - name: CHECKPOINT
        value: /checkpoint/weather-raw
      - name: BRONZE_PATH
        value: /checkpoint/bronze_parquet
      - name: MAX_OFFSETS
        value: "5000"
      - name: LOG_LEVEL
        value: WARN
    volumeMounts:
      - name: checkpoint
        mountPath: /checkpoint

  executor:
    instances: 2
    cores: 1
    memory: 1g
    serviceAccount: spark
    env:
      - name: KAFKA_BOOTSTRAP
        value: kafka-kafka-bootstrap.data.svc.cluster.local:9092
      - name: KAFKA_TOPIC
        value: weather-raw
      - name: CHECKPOINT
        value: /checkpoint/weather-raw
      - name: BRONZE_PATH
        value: /checkpoint/bronze_parquet
      - name: MAX_OFFSETS
        value: "5000"
      - name: LOG_LEVEL
        value: WARN
    volumeMounts:
      - name: checkpoint
        mountPath: /checkpoint

  volumes:
    - name: checkpoint
      persistentVolumeClaim:
        claimName: spark-checkpoint-pvc
