apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: kafka
  namespace: data
spec:
  kafka:
    version: 4.0.1
    metadataVersion: 4.0-IV1

    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false

    config:
      num.partitions: 3
      default.replication.factor: 3
      min.insync.replicas: 2

      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2

      auto.create.topics.enable: "false"

  entityOperator:
    topicOperator: {}
    userOperator: {}
