apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-application-creator
rules:
  - apiGroups: ["sparkoperator.k8s.io"]
    resources: ["sparkapplications"]
    verbs: ["create", "get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-application-creator-binding
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: default
roleRef:
  kind: ClusterRole
  name: spark-application-creator
  apiGroup: rbac.authorization.k8s.io
